// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yumsqjykylhspozmfoza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1bXNxanlreWxoc3Bvem1mb3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTc3ODEsImV4cCI6MjA2MDk3Mzc4MX0.gAJek0GtLy4FRu3_ZPTmal3pUvM3FdqnZYOGR0fskRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);